app:
  datasource:
    jdbc-url: jdbc:hsqldb:file:db/dogs
    password: sa
    username: sa
    driver-class-name: "org.hsqldb.jdbc.JDBCDriver"
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update